# docker-compose.yml
version: '3.8'

services:
  postgres-quizmaker:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=nestuser
      - POSTGRES_PASSWORD=nestpassword
      - POSTGRES_DB=nestdb
      - PGPORT=5438
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5438:5438'
    networks:
      - quizmaker-network
  quizmaker-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizmaker-api
    ports:
      - '3013:3013'
    depends_on:
      - postgres-quizmaker
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /app/prisma
    networks:
      - quizmaker-network
    restart: unless-stopped
    environment:
      - DATABASE_HOST=postgres-quizmaker
      - DATABASE_PORT=5438
      - DATABASE_USER=nestuser
      - DATABASE_PASSWORD=nestpassword
      - DATABASE_URL=postgres://nestuser:nestpass@postgres-quizmaker:5438/nestdb

volumes:
  postgres:
    driver: local
networks:
  quizmaker-network:
    external: true
