# docker-compose.yml
version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quizmaker-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5438:5432'
    networks:
      - quizmaker-network
  quizmaker-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quizmaker-api
    ports:
      - '3013:3013'
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
      - /app/prisma
    networks:
      - quizmaker-network
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
volumes:
  postgres:
  minio_data:
    driver: local
networks:
  quizmaker-network:
    external: true
